### ISSUE TITLE
Paired reads

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#134]
Thinking about a way to extract some information from paired reads to enhance our assignments. Denis Mestivier asked me if we were doing this during our last meeting.
It would be probably simpler to preprocess them, improve reads' quality and then just pass them to our current pipeline, as we may have already discussed.

**Comment by simonepignotti** [comment]
@salikhov-kamil could you implement this feature in prophyle_index query?

**Comment by karel-brinda** [comment]
@simonepignotti Simone, why do you want to implement it in `prophyle_index query`? You can use the same approach as Kraken does – even the same script.

**Comment by simonepignotti** [comment]
Yes Karel you are right, sorry. We can merge them in `prophyle classify` and pass them to `prophyle_index` already merged.
