### ISSUE TITLE
Propagation error for internal nodes associated to a fasta file

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#144]
From experimental results I noticed that no read coming from an internal node was assigned correctly. This is very likely to be an important bug, even if I haven't manually checked the index yet, and this situation is quite common with NCBI data. It would be good to add a unit test for it.

**Comment by karel-brinda** [comment]
@simonepignotti Simone, I think that this problem is already solved. Is it really so?

**Comment by simonepignotti** [comment]
Yes @karel-brinda, if we agree not to support them.

**Comment by karel-brinda** [comment]
What do you currently do in the NCBI trees? Do you move these sequences to the leaves?

**Comment by simonepignotti** [comment]
- Old RefSeq: ignore the few sequences without strain-taxid (the support for strain taxid was ended few months before the last update of the old RefSeq)
- New RefSeq: use species taxid (all fasta files are associated to the species node, and there is no way to distinguish different strain). This could be improved by creating a new leaf for each file, and assigning a fake taxid to it.
