### ISSUE TITLE
NHX tree construction using "prophyle ncbitree"

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#161]
Since databases like HMP and Viruses can change, we should build trees when the library is downloaded.

**Comment by karel-brinda** [comment]
@simonepignotti Simone, what's the current state of this issue, please?

**Comment by simonepignotti** [comment]
@karel-brinda it's basically ready, check out the libraries branch where I call `prophyle_ncbitree.py` at download time. I can integrate it as a stand alone command too, it would be just a parser for `prophyle_ncbitree.py` in the main program.

**Comment by karel-brinda** [comment]
Moving trees & FASTA files to Zenodo fixed this problem. However, we should provide a script to create a database from custom FASTA files. I will create a new issue for that.
