### ISSUE TITLE
Download sequences from accession during propagation

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#165]
At least for trees containing sequences from the NCBI database only, we could download the FASTA files during propagation using the accession number information. This is a further enhancement to what Karel proposed [here](https://github.com/karel-brinda/ProPhyle/issues/162), and should be implemented only after that.

**Comment by karel-brinda** [comment]
Since this feature might bring many problems, I am going to close it for now. If someone is interested in non-standard datasets, he can create it locally and then upload hem to Zenodo.
