### ISSUE TITLE
Split HMP fasta after download

### ISSUE THREAD

**Issue by simonepignotti** [karel-brinda/prophyle#186]
Since all HMP sequence are in the same fasta file and we do not support fasta offsets yet (see #143), we need to split it after download. This is just a temporary solution.

**Comment by karel-brinda** [comment]
@simonepignotti  Simone, what's the current state of this issue, please?

**Comment by simonepignotti** [comment]
This is our current way to store HMP sequences in the tree, we can close it but we should think about the multiple sequences support.
