### ISSUE TITLE
Visualization of outputs?

### ISSUE THREAD

**Issue by GeoMicroSoares** [karel-brinda/prophyle#201]
What software/or just how do you analyse prophyle outputs at this point?

**Comment by simonepignotti** [comment]
We are currently working on this. In the branch otu_table you can find a first prototype which creates raw otu tables from the output of ProPhyle. By "raw" I mean that it only counts the number of reads assigned to OTUs at a specific rank, without any adjustment. The output is a tsv file which I usually visualise as a heatmap.
If this does not fit your needs, we would be happy to receive any feedback and advice.

**Comment by GeoMicroSoares** [comment]
Will try it out then!
BTW, noticed how classify also outputs to a kraken format. If you could adapt the output to have taxonomy as well, pavian (https://github.com/fbreitwieser/pavian) could easily generate interesting quick visualisations!

**Comment by simonepignotti** [comment]
Nice, don't hesitate to ask for clarifications, the script is not well documented yet. To have the taxonomy in Kraken's output you could rename nodes to taxids using ete3; we switched to node names because the taxid is not always available (e.g. custom phylogenetic trees). I can provide an example if needed.

**Comment by karel-brinda** [comment]
@simonepignotti Now we are reporting assignments through node names, but we could easily add an option to specify any ETE3 attribute. Such an update would be trivial. Btw. how complicated would be to support also Kraken output format to make ProPhyle easy to incorporate into existing Kraken pipelines?

**Comment by simonepignotti** [comment]
I have been looking at this during the past couple of days, it would not take long. I think it is worth opening an issue for it.

**Comment by simonepignotti** [comment]
@karel-brinda unfortunately no, to use Pavian we should adopt the same output as Kraken, Centrifuge or Metaphlan (or to fork their repo and add a parser for our format)

**Comment by karel-brinda** [comment]
@simonepignotti Maybe we could add this output format easily. I think we could provide files like `outpref.kraken....`, `outpref.bracken....`, `outpref.centrifuge....`, `outpref.metaphlan...`, etc.
