### ISSUE TITLE
Random order of alignments due to unordered dicts

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/prophyle#227]
A bug report from an e-mail from @salikhov-kamil : There is a minor problem in prophyle_assignment.py: in case of many nodes with the same score, they are put in the output in the random way due to using unordered dictionary.

In my code (assignment_cpp), I output them in the same order as they appear in the input string.

**Comment by karel-brinda** [comment]
@salikhov-kamil We should be very careful with this issue. It could be easily solved by using `collections. OrderedDict` instead of `dict`, but it could significantly slow down the whole program. Some people report that `OrderedDict` is about 10x slower than `dict`.

**Comment by salikhov-kamil** [comment]
@karel-brinda we can even do not fix this, if c++ implementation will be used as default soon
or we can somehow use arrays instead of maps

**Comment by karel-brinda** [comment]
Even when if we are going to replace the Python implementation by your C++ implementation, they should provide identical results. It is very useful for testing as we can independently check if the code is correct. What about sorting the nodes lexicographically? This is well defined and (hopefully) easy to implement.

**Comment by salikhov-kamil** [comment]
I agree about testing and so on.
Good idea to store nodes lexicographically, but if there are multiple nodes, then sorting will add log N multiplier, while now everything works in linear time in C++ :(

**Comment by karel-brinda** [comment]
@salikhov-kamil Kamil, what's the current order in your C++ implementation? What exactly do you mean by "input string" here?

**Comment by salikhov-kamil** [comment]
Suppose that the input string (after matching) contains kmer matching info
n1,n2: 2 n3,n4: 1 n4: 1
Then I'll output nodes in the order n1, n2, n4, in the same order as they appeared in this string

**Comment by karel-brinda** [comment]
Final decision: we will not guarantee the same order of assignments and of tags as it would at a cost of performance overhead.
