### ISSUE TITLE
AssertionError: File "idx_all/index.fa.13.klcp" does not exist.

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/prophyle#254]
A report from @simonepignotti 

the tests just finished, there was an error with the last one: when using prophyle index with option -K (skip k-LCP construction), prophyle.py still tests the existence of the file for classification:
```[prophyle] 2017-09-12 00:51:17 Automatic detection of k-mer length: k=13
Traceback (most recent call last):
  File "../../prophyle/prophyle.py", line 1479, in <module>
    main()
  File "../../prophyle/prophyle.py", line 1422, in main
    cimpl=args.cimpl,
  File "../../prophyle/prophyle.py", line 824, in prophyle_classify
    pro.test_files(klcp_fn)
  File "/mnt/disk/pignotti/git_prophyle/prophyle/prophylelib.py", line 379, in test_files
    assert os.path.isfile(fn), 'File "{}" does not exist.'.format(fn)
AssertionError: File "idx_all/index.fa.13.klcp" does not exist.
make: *** [Makefile:90: .complete.git.all] Error 1
```

It is from `.complete.git.all` in testB00

Everything else is working

**Comment by karel-brinda** [comment]
I think this is already fixed in devel. Simone, could you check it, please?

**Comment by karel-brinda** [comment]
@simonepignotti Could you a provide a small simplified example with this error? I can't replicate it. Thanks.

**Comment by karel-brinda** [comment]
@simonepignotti Does this issue still exist?

**Comment by simonepignotti** [comment]
@karel-brinda sorry for the delay, it was fixed in devel as you thought.
